image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: open-preview

tasks:
  - before: >
      source ~/.bashrc
  - init: |
      sudo mkdir -p public/uploads
      sudo mkdir -p src/ratpack/public/uploads
    command: |
      gradle shadowJar
      java -jar build/libs/QualiDoK.jar
  - command: gp await-port 3000 && gp preview "$(gp url 3000)/"
