image:
  file: .gitpod.Dockerfile

ports:
  - port: 3306 # mysql
    onOpen: ignore
  - port: 8080 # LogicalDOC CE
    onOpen: ignore
  - port: 3000 # QualiDoK
    onOpen: open-browser

tasks:
  - before: >
      source ~/.bashrc
  - init: |
      sudo chmod +x gradlew
      sudo chmod +x create-directories.sh
      ./create-directories.sh
      git clone https://github.com/bitsnaps/logicaldoc-ce.git logicaldoc
      cd logicaldoc
      docker-compose up --no-start
      cd ..
    command: |
      cd logicaldoc
      docker-compose up -d
      cd ..
      ./gradlew shadowJar
      java -jar build/libs/QualiDoK.jar
  - command: gp await-port 3000 && gp preview "$(gp url 3000)/"
