image:
  file: .gitpod.Dockerfile

ports:
  - port: 3306 # MySQL
    onOpen: ignore
  - port: 8080 # LogicalDOC CE
    onOpen: open-preview
  - port: 3000 # QualiDoK
    onOpen: open-browser

tasks:
  - before: >
      source ~/.bashrc
  - init: |
      sudo chmod +x gradlew
      sudo chmod +x create-directories.sh
      ./create-directories.sh
      git clone https://github.com/logicaldoc/logicaldoc-ce.git logicaldoc
      cd logicaldoc
      git checkout 8.6.1
      echo "you should run /setup to configure LogicalDOC"
      docker-compose up --no-start
      cd ..
    command: |
      cd logicaldoc
      docker-compose up -d
      cd ..
      ./gradlew shadowJar
      java -jar build/libs/QualiDoK.jar
  - command: gp await-port 3000 && gp preview "$(gp url 3000)/"

# You can send request to this endpoint using:
#curl -X GET 'http://0.0.0.0:8080/services/rest/folder/listChildren?folderId=4' -H 'accept: application/json' -H 'authorization: Basic YWRtaW46YWRtaW4=' -H 'cache-control: no-cache'
# or
#curl -u admin:admin -H 'Accept: application/json' http://0.0.0.0:8080/services/rest/folder/listChildren?folderId=4
