# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gradle Build

on:
  push:
    branches: [ master, dev, test ]
  pull_request:
    branches: [ master ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: logicaldoc
          MYSQL_USER: ldoc
          MYSQL_PASSWORD: changeme
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=10

      #Please note that the --link option is a legacy feature of Docker and might not be available in future versions.
      logicaldoc:
        image: logicaldoc/logicaldoc-ce:8.6.1
        env:
          DB_ENGINE: mysql
          DB_HOST: mysql
          DB_PORT: 3306
          DB_NAME: logicaldoc
          DB_USER: ldoc
          DB_PASSWORD: changeme
        ports:
          - 8080:8080
        options: --link mysql:mysql --health-cmd "curl -f http://127.0.0.1:8080 || exit 1"
    steps:
      - name: Verify services
        run: |
          curl http://localhost:8080
  build:
    runs-on: ubuntu-latest
    steps:
      # We'll use "wait-on-check-action" instead of "needs" here
      #    needs: prepare
      - name: Wait on check
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          check-name: "Verify services"

      - name: Check out
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

#      - name: Validate Gradle wrapper
#        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.5.1
#        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
#        with:
#          arguments: build
#      - uses: actions/upload-artifact@v2
#        with:
#          name: Package
#          path: build/libs
# you may need to: git update-index --chmod=+x gradlew
      - name: Execute Gradle build
        run: ./gradlew build
# Build and save a report
#      - name: Upload build reports
#        uses: actions/upload-artifact@v3
#        with:
#          name: build-reports
#          path: build/reports/